### PR TITLE
Add test for survey in Challenges

### PR DESCRIPTION
**Pull request by LauraJaimeC**
- System test for surveys in challenges
- Changes in CHANGELOG

### CODE REVIEW

**Comment by LauraJaimeC** [comment]
The tests that fail are of GraphQL.

**Comment by tramuntanal** [comment]
We must fix them anyway @LauraJaimeC .
Probably related with the GraphQL canges in Decidim v0.24 required to upgrade to Rails 6 in v0.25.

I'd recommend looking for the PR in Decidim and see what changed. The PR belongs to Alexandru Lupu.

**Comment by LauraJaimeC** [comment]
> We must fix them anyway @LauraJaimeC .
> Probably related with the GraphQL canges in Decidim v0.24 required to upgrade to Rails 6 in v0.25.
> 
> I'd recommend looking for the PR in Decidim and see what changed. The PR belongs to Alexandru Lupu.

Solved!

**Review by tramuntanal — APPROVED** [review]
Yess!

**Pull request merged**
